CREATE TABLE `casos` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`corresponsal` text NOT NULL,
	`nro_caso_assistravel` text NOT NULL,
	`nro_caso_corresponsal` text,
	`fecha_inicio` text,
	`pais` text,
	`fee` real,
	`costo_usd` real,
	`monto_agregado` real,
	`costo_moneda_local` real,
	`simbolo_moneda` text,
	`informe_medico` integer DEFAULT false,
	`tiene_factura` integer DEFAULT false,
	`fecha_emision_factura` text,
	`fecha_vencimiento_factura` text,
	`fecha_pago_factura` text,
	`nro_factura` text,
	`estado_interno` text DEFAULT 'Abierto',
	`estado_caso` text DEFAULT 'On Going',
	`observaciones` text,
	`created_at` integer,
	`updated_at` integer
);
